---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: document
  path: content/site-settings.json
  label: Site Settings
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - layout
- type: heading
  label: Settings
upload_dir: ''
public_path: https://forestry-gatsby-site.s3.us-east-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
