---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: featured_image
  type: file
  config:
    maxSize: 250
  label: Featured Image
pages:
- content/projects/unforgetable-sources.md
